name: ci-cd

on:
  push:
    branches: ["main"]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: List directories
        run: ls -la

      - name: Install dependencies
        run: npm install

      - name: Build the Vite app
        run: npm run build
