name: ci-cd

on:
  push:
    branches: ["main"]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello-step
        run: echo "Hello from github actions"

      - name: Clone Repository
        uses: actions/checkout@v3

      - name: List directories
        run: ls -la

  bye:
    runs-on: ubuntu-latest

    steps:
      - name: Bye-step
        run: echo "Bye Bye!"

  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the Vite app
        run: npm run build
